SELECT
    CAR.CAR_ID,
    CAR.CAR_TYPE,
    ROUND(CAR.MONTHLY_FEE * (100 - DISCOUNT.DISCOUNT_RATE) / 100) AS FEE
FROM
    (
        SELECT
            CAR_ID,
            CAR_TYPE,
            DAILY_FEE * 30 AS MONTHLY_FEE
        FROM
            CAR_RENTAL_COMPANY_CAR
        WHERE
            CAR_TYPE IN ('세단', 'SUV')
    ) CAR
LEFT JOIN
    (
        SELECT
            CAR_TYPE,
            DISCOUNT_RATE
        FROM
            CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE
            DURATION_TYPE = '30일 이상'
    ) DISCOUNT
    ON CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
WHERE
    ROUND(CAR.MONTHLY_FEE * (100 - DISCOUNT.DISCOUNT_RATE) / 100) >= 500000
    AND ROUND(CAR.MONTHLY_FEE * (100 - DISCOUNT.DISCOUNT_RATE) / 100) < 2000000
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
        WHERE
            HISTORY.CAR_ID = CAR.CAR_ID
            AND HISTORY.START_DATE <= DATE('2022-11-30')
            AND HISTORY.END_DATE >= DATE('2022-11-01')
    )
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR.CAR_ID DESC;
